routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GenderController;
use App\Http\Controllers\StyleController;
use App\Http\Controllers\LabelController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\BandController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\TrackController;
use App\Http\Controllers\ArtistController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ArtistTrackController;




Route::get('/', function () {
    return view('welcome');
});

Route::prefix('admin')->group(function () {
    Route::get('/', function () { return view('admin');});
    Route::get('/usuarios', function () { return view('usuarios');});
});

Route::resource('genders', GenderController::class)->names('genders');
Route::resource('genders.styles', StyleController::class)->shallow();
Route::resource('labels', LabelController::class)->names('labels');
Route::resource('countries', CountryController::class)->names('countries');
Route::post('/search-countries', [CountryController::class, 'fetch'])->name('search.fetch');
Route::resource('bands', BandController::class)->names('bands');
/* Route::post('/search-bands', [BandController::class, 'fetch'])->name('search.band'); */
Route::resource('bands.members', MemberController::class)->shallow();
Route::resource('bands.albums', AlbumController::class)->shallow();
Route::resource('albums.tracks', TrackController::class)->shallow();
Route::resource('tracks.artist_tracks', ArtistTrackController::class)->shallow();
Route::resource('artists', ArtistController::class)->names('artists');

app/Models/Band.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Album;
use App\Models\Country;
use App\Models\Artist;

class Band extends Model
{
    use HasFactory;

    protected $table = 'bands';

    protected $fillable = ['name', 'country_id'];

    public function artists()
    {
        return $this->belongsToMany(Artist::class, 'members', 'artist_id', 'band_id')->withTimestamps();
    }

    public function albums()
    {
        return $this->hasMany(Album::class, 'band_id');
    }

    public function country()
    {
        return $this->belongsTo(Country::class,'country_id');
    }

    public function members()
    {
        return $this->hasMany(Member::class, 'band_id');
    }

}

app/Http/Controllers/BandController.php
<?php

namespace App\Http\Controllers;

use App\Models\Band;
use App\Models\Country;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class BandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bands = Band::with('country')
        ->withCount('members','albums')
        ->orderBy('id', 'Desc')->paginate(5);
        
        return view('bands.index', compact('bands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $countries = Country::all();
        return view('bands.create',compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'country_id' =>    'required|integer',
            'name' =>   'required|max:50',
        ]);

        Band::create($request->all());   
    
        return redirect()->route('bands.index')->with('band_store', 'Bands Created');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */
    public function show(Band $band)
    {   
        $countries = Country::all();

        return view('bands.show', compact('band', 'countries'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */
    public function edit(Band $band)
    {
        $countries = Country::all();
        return view('bands.edit',compact('band','countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Band $band)
    {
        $request->validate([
            'country_id' =>    'required|integer',
            'name' =>   'required|max:50',
        ]);

        $band->update($request->all());

        return redirect()->route('bands.index', $band)->with('band_update', 'Band updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */
    public function destroy(Band $band)
    {
        if($band->albums()->count()){
            return back()->with('band_destroy', 'Record associated with foreign key');
        }
        $band->delete();
        return back()->with('band_destroy','Band Deleted');
    }

    /* public function fetch(Request $request)
    {
     if($request->get('query'))
     {
      $query = $request->get('query');

      $data = DB::table('countries')
        ->where('name', 'LIKE', "%{$query}%")
        ->get();
      $output = '<ul class="dropdown-menu" style="display:block; position:relative">';

      foreach($data as $row)
      {
       $output .= '
       <li><a href="#">'.$row->name.'</a></li>
       ';
      }

      $output .= '</ul>';
      echo $output;

     }

     
    } */
}

resources/views/bands/create.blade.php
@extends('layouts.main')

@section('title', 'Create Band')

@section('content')

<div class="card">
    <h5 class="card-header">Create Band</h5>
    <div class="card-body">
        <form method="POST" action="{{route('bands.store')}}">
            @csrf
            <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
                        </div>
                        <select name="country_id" class="form-control">
                          <option class="hidden" selected disabled>Countries</option>
                          @foreach ($countries as $country)
                            <option value="{{ $country->id }}">
                              {{ $country->name }}</option>
                          @endforeach
                      </select>
                    </div>
                    @error('country_id')
                    <p class="help is-danger" style="color: red">{{ $message }}</p>
                    @enderror

              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
              @error('name')
              <p class="help is-danger" style="color: red">{{ $message }}</p>
              @enderror
            </div>
          
          <div class="modal-footer">
            <a type="button" class="btn btn-success" href="{{ route('bands.index') }}">Back</a>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>
        </form>
    </div>
  </div>
    
@endsection

{{-- @section('scripts')    

<script>
$(document).ready(function(){

  $('#country_name').keyup(function(){ 
        var query = $(this).val();
        if(query != '')
        {
          var _token = $('input[name="_token"]').val();
          $.ajax({
          url:"{{ route('search.band') }}",
          method:"POST",
          data:{query:query, _token:_token},
          success:function(data){
            $('#countryList').fadeIn();  
            $('#countryList').html(data);

          }
    });

    $(document).on('click', 'li', function(){  
        $('#country_name').val($(this).text());  
        $('#countryList').fadeOut();
    });



  });
</script>
@endsection --}}

resources/views/bands/edit.blade.php
@extends('layouts.main')

@section('title', 'Update Bands')

@section('content')
<br>
  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h2>Edit Bands</h2>
                </div>
                <div class="card-body">
                  <form method="POST" action="{{route('bands.update', $band)}}">
                    @csrf
                    @method('PUT')
            
                    <div class="form-group">
                    <label for="exampleFormControlSelect1">List Countries</label>
                    <select class="form-control" id="countries" name="country_id">
                        <option class="hidden" disabled>List Countries</option>
                        @foreach ($countries as $country)
                          <option value="{{ $country->id }}"
                            @if ($country->id === $band->country_id)
                                selected
                            @endif
                            >
                            {{ $country->name }}</option>
                        @endforeach
                    </select>
                    @error('country_id')
                    <p class="help is-danger" style="color: red">{{ $message }}</p>
                    @enderror
                      <label for="name">Name Band</label>
                      <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $band->name )}}">
                      @error('name')
                    <p class="help is-danger" style="color: red">{{ $message }}</p>
                    @enderror
                    </div>
                    
                    <a type="button" class="btn btn-success" href="{{ route('bands.index') }}">Back</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/bands/index.blade.php
@extends('layouts.main')

@section('title', 'Bands')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Bands</h1>
    <a href="{{ route('bands.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-user fa-sm text-white-50 Create"></i>Create</a>
</div> 


<div class="row">
    @include('custom.message')
</div>

<!-- List bands -->
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Bands</th>
        <th scope="col">Albums</th>
        <th scope="col">Countries</th>
        <th scope="col">Members</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     @foreach ($bands as $band)
     <tr>
        <td scope="row">{{ $band->id }}</td>
        <td scope="row"><a href="{{ route('bands.show', $band->id) }}">{{ $band->name }}</a></td>
        <td scope="row">
          <a href="{{ route('bands.albums.index', $band)}}">{{ $band->albums_count}}</a>
        </td>
        <td scope="row">{{ $band->country->name}}</td>
        <td scope="row"><a href="{{ route('bands.members.index', $band) }}">{{ $band->members_count}}</a></td>
        <td scope="row"><a href="{{ route('bands.edit', $band) }}" class="btn btn-primary">
        <i class="fa fa-edit"></i>
        </a></td>
        <td scope="row">
        <button class="btn btn-warning btnEliminar" data-id="{{ $band->id }}" data-toggle="modal" data-target="#modalEliminar"><i class="fa fa-trash"></i></button>
          <form action="{{ route('bands.destroy', $band) }}" id="formEli_{{ $band->id}}" method="POST">
            @csrf
           {{-- @method('DELETE') --}}
            <input type="hidden" name="id" value="{{ $band->id }}">
            <input type="hidden" name="_method" value="delete">
            
          </form>
        </td>
      </tr>
     @endforeach
    </tbody>
  </table>
  <span>
    {{ $bands->links() }}
  </span>

<!-- Modals -->
{{-- @include('bands.modalCreate') --}}
@include('bands.modalDelete')
<!-- EndModals -->

@endsection

@section('scripts')
      <script>

        var idEliminar = 0;

          $(document).ready(function(){
            /* @if($message = session('ErrorInsert'))
                $('#Create').modal('show');
            @endif */
            $(".btnEliminar").click(function(){
                idEliminar = $(this).data('id');
            });
            $(".btnModalEliminar").click(function(){
                $("#formEli_" + idEliminar).submit();
            });

          });
      </script>
  @endsection

resources/views/bands/modalCreate.blade.php
<div class="modal fade" id="modalCreate" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create Gender</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{{route('bands.store')}}">
                @csrf
        
                <div class="form-group">
              
                  <div class="form-group">
                      <label for="exampleFormControlSelect1">List Countries</label>
                      <select class="form-control" id="exampleFormControlSelect1" name="country_id">
                          @foreach ($countries as $country)
                            <option value="{{ $country->id }}">{{ $country->name }}</option>
                          @endforeach
                      </select>
                  </div>
  
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
                <span style="color: red">@error('name'){{$message}}@enderror</span>
              </div>
              
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
              </div>
            </form>
        </div>
        
      </div>
    </div>
  </div>

resources/views/bands/modalDelete.blade.php
<div class="modal fade" id="modalEliminar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Band</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                  <h5>Can you delete band?</h5>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger btnModalEliminar">Delete</button>
                  </div>
            </div>
            
          </div>
        </div>
      </div>

resources/views/bands/show.blade.php
@extends('layouts.main')

@section('title', 'Show Band')

@section('content')

<div class="card">
    <h5 class="card-header">Show Band</h5>
    <div class="card-body">
        <form>
            <div class="form-group">
              
                <div class="form-group">
                    <label for="exampleFormControlSelect1">List Countries</label>
                    <select disabled class="form-control" id="countries" name="countries">
                        <option class="hidden" disabled>List Countries</option>
                        @foreach ($countries as $country)
                          <option value="{{ $country->id }}"
                            @if ($country->id === $band->country_id)
                                selected
                            @endif
                            >
                            {{ $country->name }}</option>
                        @endforeach
                    </select>
                </div>

              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $band->name) }}" disabled>
            </div>
          
          <div class="modal-footer">
            <a type="button" class="btn btn-success" href="{{ route('bands.index') }}">Back</a>
          </div>
        </form>
    </div>
  </div>
    
@endsection