routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GenderController;
use App\Http\Controllers\StyleController;
use App\Http\Controllers\LabelController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\BandController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\TrackController;
use App\Http\Controllers\ArtistController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ArtistTrackController;




Route::get('/', function () {
    return view('welcome');
});

Route::prefix('admin')->group(function () {
    Route::get('/', function () { return view('admin');});
    Route::get('/usuarios', function () { return view('usuarios');});
});

Route::resource('genders', GenderController::class)->names('genders');
Route::resource('genders.styles', StyleController::class)->shallow();
Route::resource('labels', LabelController::class)->names('labels');
Route::resource('countries', CountryController::class)->names('countries');
Route::post('/search-countries', [CountryController::class, 'fetch'])->name('search.fetch');
Route::resource('bands', BandController::class)->names('bands');
/* Route::post('/search-bands', [BandController::class, 'fetch'])->name('search.band'); */
Route::resource('bands.members', MemberController::class)->shallow();
Route::resource('bands.albums', AlbumController::class)->shallow();
Route::resource('albums.tracks', TrackController::class)->shallow();
Route::resource('tracks.artist_tracks', ArtistTrackController::class)->shallow();
Route::resource('artists', ArtistController::class)->names('artists');

app/Models/Track.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Track extends Model
{
    use HasFactory;

    protected $table = 'tracks';

    protected $fillable = ['name','duration','album_id', 'style_id'];

    public function artists()
    {
        return $this->belongsToMany(Artist::class, 'artist_track', 'artist_id','track_id', 'partipation_id')->withTimestamps();
    }

    public function style()
    {
        return $this->belongsTo(Style::class, 'style_id');
    }

    public function albums()
    {
        return $this->belongsTo(Album::class, 'album_id');
    }

    public function relArtistsTracks()
    {
        return $this->hasMany(ArtistTrack::class, 'track_id');
    }




}

app/Http/Controllers/TrackController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use App\Models\Band;
use App\Models\Participation;
use App\Models\Style;
use App\Models\Track;
use Illuminate\Http\Request;

class TrackController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Album $album)
    {
        $tracks = $album->tracks()
        ->withCount('relArtistsTracks')->orderBy('id', 'desc')->paginate(5);
 
        $band = $album->bands;

        return view('tracks.index ', compact('tracks','album', 'band'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Album $album)
    {
        $styles = Style::all();
        return view('tracks.create', compact('styles','album'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Album $album)
    {
        $request->validate([
            'style_id' =>  'required|integer',
            'name' =>   'required|max:50',
            'duration' =>   'required|integer',
        ]);
        
        $album->tracks()->create($request->all());

        return redirect()->route('albums.tracks.index',compact('album'))->with('track_store','Track Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function show(Track $track)
    {
        $style = $track->style;
        $album = $track->albums;   
        return view('tracks.show', compact('style', 'track', 'album'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function edit(Track $track)
    {   
        $styles = Style::all();
        $album = $track->albums;
        return view('tracks.edit', compact('track','styles', 'album'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Track $track)
    {
        $request->validate([
            'style_id' =>  'required|integer',
            'name' =>   'required|max:50',
            'duration' =>   'required|integer',
        ]);

        $track->update($request->all());
        $album = $track->albums;

        return redirect()->route('albums.tracks.index', compact('track', 'album'))->with('track_update','Track Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function destroy(Track $track)
    {
        if($track->albums()->count()){
            return redirect()->back()->with('track_destroy','Record associated with foreign key');  
        }
        $track->delete();
        return redirect()->back()->with('track_destroy','Track Deleted');
    }
}

resources/views/tracks/create.blade.php
@extends('layouts.main')

@section('title', 'Create Tracks')

@section('content')

<div class="container-sm">
  <form method="POST" action="{{route('albums.tracks.store', $album)}}">
    @csrf
    <div class="form-group">
        <h3>Create Tracks</h3>
            <br>
            {{-- Styles List --}}
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
                </div>
                <select name="style_id" class="form-control">
                  <option class="hidden" selected disabled>Styles</option>
                  @foreach ($styles as $style)
                    <option value="{{ $style->id }}">
                      {{ $style->name }}</option>
                  @endforeach
              </select>
            </div>
            @error('style_id')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
            @enderror
  
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
      @error('name')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror
  
      <label for="name">Duration</label>
      <input type="number" class="form-control" id="duration" name="duration" value="{{ old('duration') }}">
      @error('duration')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror
    </div>
  
  <div class="modal-footer">
    <a href="{{ route('albums.tracks.index', $album) }}" class="float-right btn btn-success">Back</a>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
  </form>
  
</div>
    
@endsection

resources/views/tracks/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit Tracks')

@section('content')
<br>

<div class="form-group">
  <form method="POST" action="{{route('tracks.update',$track)}}">
    @csrf
    @method('PUT')
    <h2>Edit Track</h2>
    {{-- Labels List --}}
    <label for="label">Styles</label>
    <div class="input-group">
        <div class="input-group-prepend">
            <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
        </div>
        <select name="style_id" class="form-control">
          @foreach ($styles as $style)
            <option value="{{ $style->id }}"
              @if ($style->id === $track->style->id)
                selected
              @endif
              >
              {{ $style->name }}
            </option>
          @endforeach
      </select>
    </div>
    <br>

    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $track->name) }}">
    @error('name')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
    @enderror

    <label for="name">Duration</label>
    <input type="number" class="form-control" id="duration" name="duration" value="{{ old('year', $track->duration) }}">
    </div>
    @error('duration')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
    @enderror
    
    <div class="modal-footer">
      <a href="{{ route('albums.tracks.index', $album) }}" class="float-right btn btn-success">Back</a>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
  
</div>
  
@endsection

resources/views/tracks/index.blade.php
@extends('layouts.main')

@section('title', 'List Tracks')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Tracks</h1>
    <a href="{{ route('albums.tracks.create', $album) }}" class="btn btn-primary">Create</a>
</div> 

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('bands.albums.index', $band) }}">Albums</a></li>
    <li class="breadcrumb-item" aria-current="page">Tracks</li>
    <li class="breadcrumb-item active" aria-current="page">{{ $album->name}}</li>
  </ol>
</nav>

<div class="row">
    @include('custom.message')
</div>

<!-- List Tracks -->
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Tracks</th>
        <th scope="col">Duration</th>
        <th scope="col">Style</th>
        <th scope="col">Participation</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     @foreach ($tracks as $track)
     <tr>
        <td scope="row">{{ $track->id }}</td>
        <td scope="row"><a href="{{ route('tracks.show', $track->id) }}">{{ $track->name }}</a></td>
        <td scope="row">{{ $track->duration }}</td>
        <td scope="row">{{ $track->style->name }}</td>
        <td scope="row"><a href="{{ route('tracks.artist_tracks.index', $track) }}">{{ $track->rel_artists_tracks_count }}</a></td>
        <td scope="row"><a href="{{ route('tracks.edit',$track) }}" class="btn btn-primary">
        <i class="fa fa-edit"></i>
        </a></td>
        <td scope="row">
        <button class="btn btn-warning btnEliminar" data-id="{{ $track->id }}" data-toggle="modal" data-target="#modalEliminar"><i class="fa fa-trash"></i></button>
          <form action="{{ route('tracks.destroy', $track) }}" id="formEli_{{ $track->id}}" method="POST">
            @csrf
            <input type="hidden" name="id" value="{{ $track->id }}">
            <input type="hidden" name="_method" value="delete">
            
          </form>
        </td>
      </tr>
     @endforeach
    </tbody>
  </table>
  <span>
    {{ $tracks->links() }}
  </span>

<div class="modal-footer">
  <a href="{{ route('bands.albums.index', $band) }}" class="float-left btn btn-success">Back</a>
</div>
<!-- Modals -->
{{-- @include('Tracks.modalCreate') --}}
@include('Tracks.modalDelete')
<!-- EndModals -->

@endsection

@section('scripts')
      <script>

        var idEliminar = 0;

          $(document).ready(function(){
            $(".btnEliminar").click(function(){
                idEliminar = $(this).data('id');
            });
            $(".btnModalEliminar").click(function(){
                $("#formEli_" + idEliminar).submit();
            });

          });
      </script>
  @endsection

resources/views/tracks/modalDelete.blade.php
<div class="modal fade" id="modalEliminar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Track</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
              <h5>Can you delete track?</h5>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger btnModalEliminar">Delete</button>
              </div>
        </div>
        
      </div>
    </div>
  </div>

resources/views/tracks/show.blade.php
@extends('layouts.main')

@section('title', 'Show Track')

@section('content')

<div class="card">
    <h5 class="card-header">Show Track</h5>
    <div class="card-body">
        <form>
            @csrf
            <div class="form-group">
              
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Styles</label>
                    <input type="text" class="form-control" id="style_id" name="style_id" value="{{ old('style_id', $style->name) }}" disabled>
                </div>

              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $track->name) }}" disabled>
            </div>
            <label for="name">Duration</label>
              <input type="text" class="form-control" id="duration" name="duration" value="{{ old('duration', $track->duration) }}" disabled>
            </div>
          
          <div class="modal-footer">
            <a type="button" class="btn btn-success" href="{{ route('albums.tracks.index', $album)}}">Back</a>
          </div>
        </form>
    </div>
  </div>
    
@endsection